### PR TITLE
have refine block use the module defined in during method calls (for …

### LINKED ISSUE #447: symbolize_key under JRuby
During the application startup, this line

```
I18n.default_locale = :ru
```

results in an error:

## What actually happened

```
Unable to load application: NoMethodError: undefined method `symbolize_key' for #<Hash:0x319d106c>
Did you mean?  symbolize_keys
               symbolize_keys!
NoMethodError: undefined method `symbolize_key' for #<Hash:0x319d106c>
Did you mean?  symbolize_keys
               symbolize_keys!
                     deep_symbolize_keys at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/core_ext/hash.rb:17
                                    each at org/jruby/RubyHash.java:1419
                        each_with_object at org/jruby/RubyEnumerable.java:1189
                     deep_symbolize_keys at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/core_ext/hash.rb:15
                      store_translations at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/backend/simple.rb:46
                               load_file at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/backend/base.rb:220
                                    each at org/jruby/RubyHash.java:1419
                               load_file at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/backend/base.rb:220
                       load_translations at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/backend/base.rb:18
                                    each at org/jruby/RubyArray.java:1792
                       load_translations at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/backend/base.rb:18
                       init_translations at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/backend/simple.rb:77
                       available_locales at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/backend/simple.rb:52
                       available_locales at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/config.rb:45
                   available_locales_set at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/config.rb:51
                       locale_available? at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n.rb:305
              enforce_available_locales! at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n.rb:311
                         default_locale= at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n/config.rb:36
                         default_locale= at /usr/src/app/vendor/bundle/jruby/2.5.0/gems/i18n-1.3.0/lib/i18n.rb:59
                                  <main> at /usr/src/app/config/initializers/locale.rb:2
```

## Versions of i18n, rails, and anything else you think is neccessary

JRuby 9.2.5
Ruby 2.5.0
Rails 5.2.2
i18n 1.3.0

### PR DESCRIPTION
**Pull request by abrandoned**
…Jruby)

Fixes #447 

based on feedback from https://github.com/jruby/jruby/issues/5054

the `refine` block need to be extended to use it's refinements if the method calls are to use the new methods (also works on MRI)

### CODE REVIEW

**Comment by radar** [comment]
Very cool. I didn’t know this was possible. My solution was going to be to move the method back out to a monkey patch.

I think to ensure JRuby compat for this gem, JRuby should be moved out of the expected failures section of the Travis config file as well. Then we can certainly claim JRuby is fixed.

**Comment by radar** [comment]
I have just pushed a new commit to your branch which limits `oj` installation to MRI Ruby versions only. I suspect this will fix the currently broken JRuby build on Travis.

Once this build is green again, I can merge this commit into master.

Thanks for your work!

**Comment by radar** [comment]
I am seeing gem installation issues happening on Travis and have attempted a remedy with 0495b3f4ea56b4cde990ce8042d3a5fff04668ec. This commit did not fix the problem.

RubyGems reported gem installation issues a few hours ago: https://status.rubygems.org/incidents/dh3cd8fjd5qw. I am guessing this problem on Travis is connected to that issue. 

I have contacted Travis and RubyGems for comment: https://mobile.twitter.com/ryanbigg/status/1080186189401878528

I'll keep trying.

**Comment by radar** [comment]
I tried letting RubyGems sort their stuff out for an hour. Seems like it is an on-going issue: https://twitter.com/rubygems_status/status/1080108119546519552. 

This PR is blocked until RubyGems issues are fixed.

**Comment by radar** [comment]
JRuby build has now passed on Travis! https://travis-ci.org/svenfuchs/i18n/jobs/474162801

**Comment by radar** [comment]
Ignoring the one failing build in that set as I think it's leftover RG issues.

**Comment by sandelius** [comment]
@radar @abrandoned  Thanks for the fix 👍

**Pull request merged**
