### PR TITLE
Expose `translations` in simple backend and load translations only when not loaded

### PR DESCRIPTION
**Pull request by PikachuEXE**
Pull Request for #254

### CODE REVIEW

**Comment by radar** [comment]
I think the Travis tests may have failed because this branch wasn't up-to-date with master. I've just pushed a commit which should fix that.

Thanks very much for making this PR!

**Comment by PikachuEXE** [comment]
many jobs have failed due to
`Your Gemfile.lock is corrupt`

**Comment by sandstrom** [comment]
@radar I think this trick may work: https://github.com/lastnpe/lastnpe.github.io/pull/2

(more details in this thread: https://github.com/bundler/bundler/issues/4467#issuecomment-251247158, especially the last comment)

**Comment by radar** [comment]
Thanks @sandstrom. I will try deleting the `Gemfile.lock` file.

**Comment by deivid-rodriguez** [comment]
Hei! Maybe CI will pass now since lock files live in source control?

**Comment by PikachuEXE** [comment]
@deivid-rodriguez build is green now after rebasing

**Comment by oniofchaos** [comment]
@PikachuEXE looks like just a merge conflict on one file. Anything I can do to help?

**Comment by PikachuEXE** [comment]
Updated code to expose `#translation` only and allow performing initialization when called with argument
The new argument is defined using optional keyword argument but should be fine since `I18n` requires ruby >= 2.0.0

**Comment by oniofchaos** [comment]
@radar from other PRs it looks like you've been the one setting up things for new versions. Pikachu tidied this up and it LGTM.

**Comment by radar** [comment]
Seems fine to me!

**Pull request merged**
