### PR TITLE
Fix default: nil with fallbacks

### LINKED ISSUE #386: default: nil breaks fallbacks
I've noticed that using `default: nil` with fallbacks leads to breaking the fallback chain.

Given these translations:
````yaml
de:
  bar: 'Bar from de'
en:
  bar: 'Bar from en'
````

`I18n.t('bar', locale: :'de-DE', default: '')` returns `'Bar from de'` 👍 
`I18n.t('bar', locale: :'de-DE', default: nil)` returns `nil` 👎 

This is caused by the return statement in this code from fallbacks.rb: (simplified for readability)
```ruby
I18n.fallbacks[locale].each do |fallback|
  result = super(fallback, key, options)
  # PROBLEMATIC STATEMENT:
  return result if (result.nil? && options.key?(:default) && options[:default].nil?) || !result.nil?
end
```
In other words: If you have a default of `nil` and the first fallback locale doesn't return a value, the default is applied immediately. The loop is exited and no further fallbacks are tried.

The solution is to delay the default check until all fallbacks are tried.

I've prepared a PR with a failing test case for this problem.  See #387

### PR DESCRIPTION
**Pull request by daniel-rikowski**
Fixes #386

### CODE REVIEW

**Comment by radar** [comment]
This will go out in the 0.9.0 release, probably next week or week after.

**Comment by rafaelfranca** [comment]
This change introduce a regression. Here is the regression test:

```diff
diff --git a/test/backend/fallbacks_test.rb b/test/backend/fallbacks_test.rb
index 23e4713..a220c03 100644
--- a/test/backend/fallbacks_test.rb
+++ b/test/backend/fallbacks_test.rb
@@ -64,6 +64,10 @@ class I18nBackendFallbacksTranslateTest < I18n::TestCase
     assert_nil I18n.t(:missing_bar, :locale => :'de-DE', :default => nil)
   end
 
+  test "returns the translation missing message if the default is also missing" do
+    assert_equal 'translation missing: de-DE.missing_bar', I18n.t(:missing_bar, :locale => :'de-DE', :default => [:missing_baz])
+  end
+
   test "returns the :'de-DE' default :baz translation for a missing :'de-DE' when defaults contains Symbol" do
     assert_equal 'Baz in :de-DE', I18n.t(:missing_foo, :locale => :'de-DE', :default => [:baz, "Default Bar"])
   end
```

**Comment by rafaelfranca** [comment]
Failure message:

```
  1) Failure:
I18nBackendFallbacksTranslateTest#test_returns_the_translation_missing_message_if_the_default_is_also_missing [/Users/rafaelfranca/src/github/i18n/test/backend/fallbacks_test.rb:68]:
--- expected
+++ actual
@@ -1 +1 @@
-"translation missing: de-DE.missing_bar"
+"translation missing: de-DE.no key"
```

**Comment by rafaelfranca** [comment]
https://github.com/svenfuchs/i18n/pull/389 should fix that regression.

**Comment by matheussilvasantos** [comment]
Awesome! Thanks @daniel-rikowski.

**Pull request merged**
